### ISSUE TITLE
Support for the slave shield? 

### ISSUE THREAD

**Issue by StimpyMGS** [wildekek/esphome-opentherm-templates#1]
Hey man, thanks for doing this! Wish I had the coding skills but I don't... Are you able to add support for the slave shield so we can connect an existing thermostat to the gateway?

**Comment by wildekek** [comment]
Unfortunately the [library](https://github.com/arthurrump/esphome-opentherm ) I depend on does not support the gateway. When it does, I will implement it.

**Comment by wildekek** [comment]
Good news, the Opentherm component is now in the [latest ESPHome release](https://esphome.io/components/opentherm). I'm closing this issue, since the ESPHome repo is the place where this should be implemented now.
